using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FlavorTexter
{
    internal static class Nouner
    {

        public static string GetNoun() => Nouns[Random.Shared.Next(0, Nouns.Length - 1)];

        public static string[] Nouns = new string[]
        {
            "content",
            "your mom",
            "your dad",
            "API",
            "aesthetics",
            "backstory",
            "tactics",
            "bugs",
            "warp drive",
            "data",
            "AI",
            "crystals",
            "spaghetti",
            "fluxgate",
            "electrons",
            "loud noises",
            "wires",
            "bytecode",
            "the truth",
            "magic",
            "hot lava",
            "bits",
            "Brad",
            "sensors",
            "photons",
            "signal",
            "the planet",
            "password",
            "chips",
            "circuits",
            "privacy",
            "synergy",
            "widgets",
            "love",
            "packets",
            "reality",
            "lasers",
            "protocols",
            "voltage",
            "registers",
            "puns",
            "kittens",
            "plot device",
            "the core",
            "dank memes",
            "subroutines",
            "radiation",
            "steam",
            "trousers",
            "beer",
            "protocol",
            "one-liners",
            "the Gibson",
            "software",
            "holograms",
            "magnets",
            "inductors",
            "resistors",
            "capacitors",
            "sausage",
            "my wife",
            "your wife",
            "drama",
            "the future",
            "vectors",
            "the clowns",
            "5G implant",
            "monkeys",
            "breadboard",
            "money",
            "the Internet",
            "fluids",
            "the impostor",
            "beats",
            "dopamine",
            "fedora",
            "neural net",
            "comments",
            "ports",
            "you. Yes you",
            "mixtape",
            "[REDACTED]",
            "hot tub",
            "paperwork",
            "Nerf",
            "the 1%",
            "the Matrix",
            "variables",
            "IP address",
            "spline"
        };
    }
}
